# Pull request validation job
jobs:
  - template: ./templates/xcuitest-e2e-template.yml
    parameters:
      name: iPhoneX_13
      iosVersion: 12.2
      xcodeVersion: 10.2
      deviceName: "iPhone X"
      tvosName: AppleTV_13
      tvosDeviceName: "Apple TV"
